
FROM node:20-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    pkg-config \
    libssl-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml tsconfig*.json nest-cli.json ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

EXPOSE 5001

CMD ["pnpm", "run", "start:dev"]
